### ISSUE TITLE
Local query service accesses data from remote wikidata instance

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/pik-wikibase#2]
The access should happen to the local database. 
There must be some configuration files or variables that need to be tweaked.

See here:
https://github.com/wikimedia/wikidata-query-gui/blob/master/default-config.json

and here: 
https://github.com/wikimedia/wikidata-query-gui/blob/master/wikibase/config.js

most likely a file named `customConfig.json` needs to be created and mounted in the built frontend image

**Comment by besendorf** [comment]
I added the hostname in the ```docker-compose.yml``` and tried example querys on wikidata.org and our wdqs instance.
Please try again, then I will close this if you confirm it

**Comment by AbdBarho** [comment]
can you tell me exactly what you added so I can test it ?

**Comment by besendorf** [comment]
I pushed now, but I mean you can test on ```aghcc-edu01.imp.fu-berlin.de:8282```
https://github.com/code-openness/pik-wikibase/commit/fe11b860b6a16ae030efe08a9375d7361009cf41

**Comment by AbdBarho** [comment]
I tried locally, did not seem to change.

I would most likely assume the problem is not in the docker file, but rather in the GUI itself, I will dig deeper in the issue.
